######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 24 10:46:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += run.cpp
