######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 24 09:36:12 2016
######################################################################
#QT       += core gui
QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
