######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 24 09:57:23 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
