######################################################################
# Automatically generated by qmake (3.0) ?? 11? 22 20:53:13 2016
######################################################################

TEMPLATE = app
TARGET = 5th
INCLUDEPATH += .

# Input
SOURCES += const.cpp inherit.cpp write.cpp
