######################################################################
# Automatically generated by qmake (3.0) ?? 11? 23 15:42:56 2016
######################################################################

TEMPLATE = app
TARGET = 1st
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
