######################################################################
# Automatically generated by qmake (3.0) ?? 11? 23 16:17:31 2016
######################################################################

TEMPLATE = app
TARGET = QT
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
QT += widgets
